package com.h3c.bigdata.zhgx.function.report.model;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * @ClassName TemplateItemBean
 * @Description TODO
 * @Author zzzzitai
 * @Date 2018/11/16 16:29
 * @Version 1.0
 **/
@Data
@NoArgsConstructor
@AllArgsConstructor
@ApiModel(value = "字段项添加")
public class TemplateItemBean {
    
    @ApiModelProperty(value = "闫参数")
    private Boolean showMinus;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_description.item
     *
     * @mbg.generated
     */
    @ApiModelProperty(value = "字段")
    private String itemName;

    @ApiModelProperty(value = "number")
    private String number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_description.name
     *
     * @mbg.generated
     */
    @ApiModelProperty(value = "字段中文名")
    private String itemDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_description.type
     *
     * @mbg.generated
     */
    @ApiModelProperty(value = "字段类型（0，字符类型；1，整数；2，小数；3，日期;4 ，枚举；5，文本）")
    private int type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_description.is_null
     *
     * @mbg.generated
     */
    @ApiModelProperty(value = "是否可为空值（0：false, 1: true）")
    private Byte isNull;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_description.enums
     *
     * @mbg.generated
     */
    @ApiModelProperty(value = "枚举类型，用逗号间隔")
    private String enums;
    
    @ApiModelProperty(value = "是否为联合唯一（0：false, 1: true）")
    private Byte isUnionOnly;
    
    @ApiModelProperty(value = "是否可搜索（0：false, 1: true）")
    private Byte isSearch=0;

    @ApiModelProperty(value = "增删标识（0：删, 1: 增，2：修改）")
    private String sign;
    @ApiModelProperty(value = "更新人")
    private String update_user;
    @ApiModelProperty(value = "更新时间")
    private String update_time;
    @ApiModelProperty(value = "编辑时字段新值")
    private String itemOldName;

    @ApiModelProperty(value = "模板id")
    private Integer templateId;

    @ApiModelProperty(value = "是否排序（1：不排序，0：排序）")
    private Byte isSort;

    public TemplateItemBean(String itemName, String itemDesc) {
        this.itemName = itemName;
        this.itemDesc = itemDesc;
    }
}
